---
- hosts: 127.0.0.1
  user: root
  roles:
    - role: setup_kvm_server

- hosts: ptmdemotmpl
  user: root
  roles:
    - role: base_vm


- hosts: 127.0.0.1
  user: root
  roles:
    - role: clone_vm

- hosts: ptmdemoservers
  user: root
  roles:
    - role: setup_ptm_demo_vms

- hosts: 127.0.0.1
  user: root
  vars:
    create_topo_py: 'create_topology.py'
  tasks:
    - name: copy lldp checker to kvm host
      copy: src=files/lldp_checker.sh dest=/tmp mode=750

    - name: wait until lldp is active on all hosts
      command: /tmp/lldp_checker.sh

    - name: copy kvm startup script generator to tmp dir of kvm host
      copy: src=files/vm_startup_script.py  dest=/tmp mode=750

    - name: create kvm startup scripts
      command: /tmp/vm_startup_script.py

    - name: shutdown all ptm demo vms
      command: virsh shutdown {{ item }}
      with_items: vmnames

#    - name: sleep for a few seconds to let vms shutdown
#      pause: seconds=10

#    - name: bring up ptm demo vms using custom script
#      command: /tmp/{{item}}_startup.sh
#      with_items: vmnames

