- include: ../../../lldp_install.yml

- include: ptm_install.yml

- name: remove firstboot file
  file: path=/root/firstboot_done state=absent

- name: remove 127.0.1.1 line from /etc/hosts
  lineinfile: dest=/etc/hosts regexp='127.0.1.1' state=absent

