
- name: install pkgs required for kvm
  apt: pkg=$item
  with_items:
    - qemu-kvm
    - libvirt-bin
    - python-vm-builder
    - bridge-utils
    - uml-utilities
    - libguestfs-tools
    - guestmount
    - gperf
    - libpcre3-dev
    - python-libvirt
    - virtinst
    - virt-viewer
    - libevent-2.0-5
    - libxml2
    - libsnmp15

- name: run update-guestfs-appliance. dependency for running virt-sysprep
  command: update-guestfs-appliance creates=/usr/lib/guestfs/supermin.d/base.img

- name: change permission on linux kernels to 0644. dependency for libguestfs
  file: path=/boot recurse=true mode=0644 state=directory

- include: clean_out_server.yml

- name: put config file for vm in tmp directory
  copy: src=vmbuilder.cfg dest=/tmp

- name: put first time bootup script in tmp dir
  template: src=boot.sh.j2 dest=/tmp/boot.sh

- name: copy ssh port checker script to tmp dir
  copy: src=ssh_port_checker.sh dest=/tmp mode=750

- name: put network base vm net definition files in tmp directory
  copy: src=basenet.xml dest=/tmp/basenet.xml

- name: put network mgmt definition files in tmp directory
  copy: src=mgmtnet.xml dest=/tmp/mgmtnet.xml

- name: put network definition files for vm links
  template: src=vmnet.xml.j2 dest=/tmp/{{item}}.xml
  with_items: vmnets_without_mgmt

- name: define vm networks
  command: virsh net-define --file /tmp/{{item}}.xml
  with_items: vmnets

- name: autostart vm networks
  command: virsh net-autostart {{item}}
  with_items: vmnets

- name: restart libvirt so networks start up
  service: name=libvirt-bin state=restarted

- name: create base directory for storing vms
  file: path={{ vmdir }}/images state=directory

- name: create basevm..takes a while.take a 10 min coffee break
  command: vmbuilder kvm ubuntu --hostname=vm1 -c /tmp/vmbuilder.cfg -d {{ vmdir }}/images/vm1 --rootsize 1024 --swapsize 256

- name: start up basevm
  command: virsh start vm1
  ignore_errors: true

- name: wait until ssh port is open
  shell: /tmp/ssh_port_checker.sh 10.100.1.2

- name: sleep for a little bit to allow ssh to startup
  pause: seconds=10
